### ISSUE TITLE
Syntax error: Line 7

### ISSUE THREAD

**Issue by schmittyd** [tryptech/obs-zoom-and-follow#22]
I've recently reset my OBS install and when I add the script into OBS I get the following error

```
[zoom_and_follow_mouse.py]   File "%USERPROFILE%/OneDrive/Software/Streaming/OBS/plugins\zoom_and_follow_mouse.py", line 7
[zoom_and_follow_mouse.py]     <!DOCTYPE html>
[zoom_and_follow_mouse.py]     ^
[zoom_and_follow_mouse.py] SyntaxError: invalid syntax
```
I have installed Python 3.6 and changed the python path to the correct location and also installed pynput and screeninfo.

**Comment by tryptech** [comment]
I don't think it's an issue with the python script itself. None of the source has any code related to HTML at all. I have a gut feeling that you downloaded the "webpage" of the script rather than the raw script itself. Try downloading the repo as a zip and extract just the .py file itself and try it in OBS again.

**Comment by schmittyd** [comment]
ok, thanks. I'll give it a try.

**Comment by schmittyd** [comment]
That worked!
