### ISSUE TITLE
Fails on window capture, type browser

### ISSUE THREAD

**Issue by leifbeaton** [tryptech/obs-zoom-and-follow#43]
If you window capture a browser, the window title can change - notably every time you navigate. This causes an indexoutofrange exception when enumerating the windows upon script triggering. Would it be an option to capture the PID of the HWND when you select the source in the script settings and use that rather than the window title?

**Comment by tryptech** [comment]
I do not know of a library at the moment that lets me do that across platforms.

Right now, if I want to get window information, my options are relatively limited. For reference, if I try to get the window information in Windows, PyWinCtl can only get me the .exe, and the window titles under that .exe; on the other hand OBS window sources can only get me the window title and the .exe. I don't have a very verbose way of doing it aside from trying write something from scratch. 

If possible, I would suggest checking if your browsesr has an option to disable changing the title info.

**Comment by tryptech** [comment]
I was reading through the source for PyWinCtl, and found the handle function and I'm trying it out now, I think I should be able to fallback on the Handle if the name changes

**Comment by leifbeaton** [comment]
Good work! Let me know if you need me to test if/when completed.

**Comment by tryptech** [comment]
@leifbeaton I have updated under the Corner-Zoom-Hotfix branch that should deal with the window title changing at least under the current running OBS instance. As long as you don't close OBS, I should track the window by handle by default since it's more reliable than title for Windows and Linux.

OBS does not track based on anything other window title so if you close OBS, change the title of the window and reopen OBS, it will fail and require you to reselect the source for the window capture. I will have to look into maybe getting OBS to update the source, but I'm not sure if doing it automatically would be a good idea if I potentially mess someone's layout up.

Please give it a try and get back to me if it works or not.

**Comment by leifbeaton** [comment]
Hi there,

 

Thanks for doing this. I am on the road at the moment, but I will give it a go over the weekend. As for having to reselect source at start of OBS, that to me seems perfectly acceptable. Having OBS track the source even though the title changes while OBS is open was my main concern. Honestly, unless someone massively disagrees with me, I don’t see the value in you spending a lot of time investigating having the source selection “survive” OBS restart - but that’s just me. Again, THANKS!!!

 

//L

**Comment by tryptech** [comment]
I'm assuming no news is good news. Please message if you have any issues and I'll reopen the ticket.
