### ISSUE TITLE
settings don't show up on obs

### ISSUE THREAD

**Issue by alexroumi** [tryptech/obs-zoom-and-follow#6]
after installing the python modules and adding the file to the obs scripts i cannot find a hot key option on the hotkey section of the settings

**Comment by tryptech** [comment]
Try filtering in the hotkeys section for "enable/disable mouse zoom" and "enable/disable mouse follow"

**Comment by alexroumi** [comment]
Nope. Doesn't work

![image](https://user-images.githubusercontent.com/59561790/115025211-c07d8a00-9ec9-11eb-9d4d-1c3a76dd7ef1.png)

**Comment by tryptech** [comment]
The only reason I can imagine it not showing up is the script not loading properly in OBS. Were there any sort of messages or errors when you added the script?

**Comment by alexroumi** [comment]
Nope not at all

**Comment by FlyMyPG** [comment]
For me, the cause of this problem was not having a python 3.6 interpreter listed on the Tools -> Scripts -> Python Settings tab.

If the script is properly installed (with a suitable Python interpreter selected), you will see the following:
1. "zoom_and_follow_mouse.py" listed under Tools -> Scripts -> Scripts -> Loaded Scripts
2. When the above script is selected (clicked once) you should see the script info to the right, including the Description and 11 settings.
3. Selecting File -> Settings -> Hotkeys then filtering for "mouse" will show the two hotkeys for this script.

**Comment by p2635** [comment]
For those who are having trouble, I had to install the required python packages installed through Python 3.6. I had to run this: `AppData\Local\Programs\Python\Python36\python -m pip install pynput screeninfo`

If I installed them normally, it wouldn't work because it would install it for python 3.9.

**Comment by alexroumi** [comment]
Sooo. long story short after downloading python 3.6.0 64 bit I was finally able to make it work.

BTW thanks for your patience
